CREATE TABLE IF NOT EXISTS `players` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `citizenid` varchar(50) NOT NULL,
  `cid` int(11) DEFAULT 1,
  `slot` int(11) DEFAULT 1,
  `license` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `money` longtext NOT NULL,
  `charinfo` longtext NOT NULL,
  `job` longtext NOT NULL,
  `gang` longtext NOT NULL,
  `position` longtext NOT NULL,
  `metadata` longtext NOT NULL,
  `inventory` longtext NULL,
  `appearance` longtext NULL,
  `weapons` longtext NULL,
  `horses` longtext NULL,
  `wagons` longtext NULL,
  `health` smallint unsigned NOT NULL DEFAULT 600,
  `stamina` smallint unsigned NOT NULL DEFAULT 100,
  `weight` int(11) DEFAULT 35000,
  `slots` int(11) DEFAULT 25,
  `last_played` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `players_citizenid_unique` (`citizenid`),
  KEY `players_license_index` (`license`),
  KEY `players_license_slot_index` (`license`, `slot`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bans` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `license` varchar(50) DEFAULT NULL,
  `discord` varchar(50) DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `expire` int(11) DEFAULT NULL,
  `bannedby` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `license` (`license`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
