Node7Shared = Node7Shared or {}
Node7Shared.Items = {

    -----------------------------------------------
    -- YOUR CUSTOM ITEMS
    -----------------------------------------------
    -- add your custom items here & check for doubles

    -----------------------------------------------
    -- CORE ITEMS
    -----------------------------------------------
    -- general items
    bread      = { name = 'bread',      label = 'Bread',         weight = 100, type = 'item', image = 'bread.png',      unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'Bread Roll' },
    water      = { name = 'water',      label = 'Water',         weight = 100, type = 'item', image = 'water.png',      unique = false, useable = true, shouldClose = true, description = 'Drinkable Water' },
    stew       = { name = 'stew',       label = 'Stew',          weight = 100, type = 'item', image = 'stew.png',       unique = false, useable = true, decay = 60, delete = true, shouldClose = true, description = 'Warm Stew' },
    beer       = { name = 'beer',       label = 'Beer',          weight = 100, type = 'item', image = 'beer.png',       unique = false, useable = true, shouldClose = true, description = 'Best beer in town' },
    coffee     = { name = 'coffee',     label = 'Coffee',        weight = 100, type = 'item', image = 'coffee.png',     unique = false, useable = true, decay = 10, delete = true, shouldClose = true, description = 'Hot Coffee' },
    canteen100 = { name = 'canteen100', label = 'Full Canteen',  weight = 500, type = 'item', image = 'canteen100.png', unique = true,  useable = true, shouldClose = true, description = 'Canteen 100% Full'},
    canteen75  = { name = 'canteen75',  label = 'Canteen',       weight = 400, type = 'item', image = 'canteen75.png',  unique = true,  useable = true, shouldClose = true, description = 'Canteen 75% Full'},
    canteen50  = { name = 'canteen50',  label = 'Canteen',       weight = 300, type = 'item', image = 'canteen50.png',  unique = true,  useable = true, shouldClose = true, description = 'Canteen 50% Full'},
    canteen25  = { name = 'canteen25',  label = 'Canteen',       weight = 200, type = 'item', image = 'canteen25.png',  unique = true,  useable = true, shouldClose = true, description = 'Canteen 25% Full'},
    canteen0   = { name = 'canteen0',   label = 'Empty Canteen', weight = 100, type = 'item', image = 'canteen0.png',   unique = true,  useable = true, shouldClose = true, description = 'Empty Canteen'},
    handcuffs  = { name = 'handcuffs',  label = 'Hand Cuffs',    weight = 100, type = 'item', image = 'handcuffs.png',  unique = false, useable = true, shouldClose = true, description = 'Used for cuffs' },

    -- horse items
    horse_brush         = { name = 'horse_brush',       label = 'Horse Brush',          weight = 100, type = 'item', image = 'horse_brush.png',                 unique = false, useable = true, shouldClose = true, description = 'Brush used to clean your horse' },
    horse_lantern       = { name = 'horse_lantern',     label = 'Horse Lantern',        weight = 100, type = 'item', image = 'horse_lantern.png',               unique = false, useable = true, shouldClose = true, description = 'To see in the dark' },
    horse_stimulant     = { name = 'horse_stimulant',   label = 'Horse Stimulant',      weight = 100, type = 'item', image = 'horse_stimulant.png',             unique = false, useable = true, shouldClose = true, description = 'Given to horses' },
    horse_reviver       = { name = 'horse_reviver',     label = 'Horse Reviver',        weight = 100, type = 'item', image = 'horse_reviver.png',               unique = false, useable = true, shouldClose = true, description = 'Given to horses' },
    horse_carrot        = { name = 'horse_carrot',      label = 'Horse Carrot',         weight = 100, type = 'item', image = 'horse_carrot.png',                unique = false, useable = true, shouldClose = true, description = 'Horses like these' },
    horse_apple         = { name = 'horse_apple',       label = 'Horse Apple',          weight = 100, type = 'item', image = 'horse_apple.png',                 unique = false, useable = true, shouldClose = true, description = 'A crisp snack for your horse' },
    sugarcube           = { name = 'sugarcube',         label = 'Sugar Cube',           weight = 100, type = 'item', image = 'sugarcube.png',                   unique = false, useable = true, shouldClose = true, description = 'Horses like these' },
    haysnack            = { name = 'haysnack',          label = 'Hay Snack',            weight = 100, type = 'item', image = 'hay_cube.png',                    unique = false, useable = true, shouldClose = true, description = 'Hay snack for horses' },
    horsemeal           = { name = 'horsemeal',         label = 'Horse Meal',           weight = 100, type = 'item', image = 'consumable_horse_meal.png',       unique = false, useable = true, shouldClose = true, description = 'A meal of oats for your horse' },

    -- animal items
    legendary_pelt = { name = 'legendary_pelt', label = 'Legendary Pelt', weight = 100, type = 'item', image = 'legendary_pelt.png', unique = false, useable = true, shouldClose = true, description = 'Legendary' },
    perfect_pelt   = { name = 'perfect_pelt',   label = 'Perfect Pelt',   weight = 100, type = 'item', image = 'perfect_pelt.png',   unique = false, useable = true, shouldClose = true, description = 'Perfect (* * *)' },
    good_pelt      = { name = 'good_pelt',      label = 'Good Pelt',      weight = 100, type = 'item', image = 'good_pelt.png',      unique = false, useable = true, shouldClose = true, description = 'Good (* *)' },
    poor_pelt      = { name = 'poor_pelt',      label = 'Poor Pelt',      weight = 100, type = 'item', image = 'poor_pelt.png',      unique = false, useable = true, shouldClose = true, description = 'Poor (*)' },
    reptile_skin   = { name = 'reptile_skin',   label = 'Reptile Skin',   weight = 100, type = 'item', image = 'reptile_skin.png',   unique = false, useable = true, shouldClose = true, description = 'snake skin' },
    feather        = { name = 'feather',        label = 'Feather',        weight = 100, type = 'item', image = 'feather.png',        unique = false, useable = true, shouldClose = true, description = 'bird feather' },
    animal_heart   = { name = 'animal_heart',   label = 'Animal Heart',   weight = 100, type = 'item', image = 'animal_heart.png',   unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'animal heart' },
    small_pelt     = { name = 'small_pelt',     label = 'Small Pelt',     weight = 100, type = 'item', image = 'small_pelt.png',     unique = false, useable = true, shouldClose = true, description = 'small animal pelt' },

    -- medical
    bandage      = { name = 'bandage',      label = 'Bandage',       weight = 100, type = 'item', image = 'bandage.png',      unique = false, useable = true, shouldClose = true, description = 'used to improve your health' },
    firstaid     = { name = 'firstaid',     label = 'First Aid',     weight = 100, type = 'item', image = 'firstaid.png',     unique = false, useable = true, shouldClose = true, description = 'used by medics to improve your health' },
    fieldbandage = { name = 'fieldbandage', label = 'Field Bandage', weight = 100, type = 'item', image = 'fieldbandage.png', unique = false, useable = true, shouldClose = true, description = 'patching yourself up' },

    -- Bird Post
    birdpost = { name = 'birdpost', label = 'Bird Post', weight = 5, type = 'item', image = 'birdpost.png', unique = false, useable = true, shouldClose = true, description = 'Bird Post for sending letters' },
    -- Physical NODE7 currency
    cash = { name = 'cash', label = 'Cash', weight = 0, type = 'item', image = 'cash.png', unique = false, useable = false, shouldClose = false, description = 'Physical cash carried by the character. Movable, droppable, and synchronized with the NODE7 cash account.' },

    -- Money Clip
    money_clip       = { name = 'money_clip',       label = 'Money Clip',       weight = 1, type = 'item', image = 'money_clip.png',       unique = true, useable = true, shouldClose = true, description = 'Money Clip' },
    blood_money_clip = { name = 'blood_money_clip', label = 'Blood Money Clip', weight = 1, type = 'item', image = 'blood_money_clip.png', unique = true, useable = true, shouldClose = true, description = 'Blood Money Clip' },

    -- fishing
    a_c_fishbluegil_01_ms        = { name = 'a_c_fishbluegil_01_ms',        label = 'Blue Gil (M)',         weight = 600,  type = 'item', image = 'a_c_fishbluegil_01_ms.png',        unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishbluegil_01_sm        = { name = 'a_c_fishbluegil_01_sm',        label = 'Blue Gil (S)',         weight = 300,  type = 'item', image = 'a_c_fishbluegil_01_sm.png',        unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishbullheadcat_01_ms    = { name = 'a_c_fishbullheadcat_01_ms',    label = 'Bullhead Cat (M)',     weight = 600,  type = 'item', image = 'a_c_fishbullheadcat_01_ms.png',    unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishbullheadcat_01_sm    = { name = 'a_c_fishbullheadcat_01_sm',    label = 'Bullhead Cat (S)',     weight = 300,  type = 'item', image = 'a_c_fishbullheadcat_01_sm.png',    unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishchainpickerel_01_ms  = { name = 'a_c_fishchainpickerel_01_ms',  label = 'Chain Pickerel (M)',   weight = 600,  type = 'item', image = 'a_c_fishchainpickerel_01_ms.png',  unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishchainpickerel_01_sm  = { name = 'a_c_fishchainpickerel_01_sm',  label = 'Chain Pickerel (S)',   weight = 300,  type = 'item', image = 'a_c_fishchainpickerel_01_sm.png',  unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishchannelcatfish_01_lg = { name = 'a_c_fishchannelcatfish_01_lg', label = 'Channel Catfish (L)',  weight = 900,  type = 'item', image = 'a_c_fishchannelcatfish_01_lg.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishchannelcatfish_01_xl = { name = 'a_c_fishchannelcatfish_01_xl', label = 'Channel Catfish (EL)', weight = 1000, type = 'item', image = 'a_c_fishchannelcatfish_01_xl.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishlakesturgeon_01_lg   = { name = 'a_c_fishlakesturgeon_01_lg',   label = 'Lake Sturgeon (L)',    weight = 900,  type = 'item', image = 'a_c_fishlakesturgeon_01_lg.png',   unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishlargemouthbass_01_lg = { name = 'a_c_fishlargemouthbass_01_lg', label = 'Large Mouth Bass (L)', weight = 900,  type = 'item', image = 'a_c_fishlargemouthbass_01_lg.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishlargemouthbass_01_ms = { name = 'a_c_fishlargemouthbass_01_ms', label = 'Large Mouth Bass (M)', weight = 600,  type = 'item', image = 'a_c_fishlargemouthbass_01_ms.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishlongnosegar_01_lg    = { name = 'a_c_fishlongnosegar_01_lg',    label = 'Long Nose Gar (L)',    weight = 900,  type = 'item', image = 'a_c_fishlongnosegar_01_lg.png',    unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishmuskie_01_lg         = { name = 'a_c_fishmuskie_01_lg',         label = 'Muskie (L)',           weight = 900,  type = 'item', image = 'a_c_fishmuskie_01_lg.png',         unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishnorthernpike_01_lg   = { name = 'a_c_fishnorthernpike_01_lg',   label = 'Northern Pike (L)',    weight = 900,  type = 'item', image = 'a_c_fishnorthernpike_01_lg.png',   unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishperch_01_ms          = { name = 'a_c_fishperch_01_ms',          label = 'Perch (M)',            weight = 600,  type = 'item', image = 'a_c_fishperch_01_ms.png',          unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishperch_01_sm          = { name = 'a_c_fishperch_01_sm',          label = 'Perch (S)',            weight = 300,  type = 'item', image = 'a_c_fishperch_01_sm.png',          unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishrainbowtrout_01_lg   = { name = 'a_c_fishrainbowtrout_01_lg',   label = 'Rainbow Trout (L)',    weight = 900,  type = 'item', image = 'a_c_fishrainbowtrout_01_lg.png',   unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishrainbowtrout_01_ms   = { name = 'a_c_fishrainbowtrout_01_ms',   label = 'Rainbow Trout (M)',    weight = 600,  type = 'item', image = 'a_c_fishrainbowtrout_01_ms.png',   unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishredfinpickerel_01_ms = { name = 'a_c_fishredfinpickerel_01_ms', label = 'Red Fin Pickerel (M)', weight = 600,  type = 'item', image = 'a_c_fishredfinpickerel_01_ms.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishredfinpickerel_01_sm = { name = 'a_c_fishredfinpickerel_01_sm', label = 'Red Fin Pickerel (S)', weight = 300,  type = 'item', image = 'a_c_fishredfinpickerel_01_sm.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishrockbass_01_ms       = { name = 'a_c_fishrockbass_01_ms',       label = 'Rock Bass (M)',        weight = 600,  type = 'item', image = 'a_c_fishrockbass_01_ms.png',       unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishrockbass_01_sm       = { name = 'a_c_fishrockbass_01_sm',       label = 'Rock Bass (S)',        weight = 300,  type = 'item', image = 'a_c_fishrockbass_01_sm.png',       unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishsalmonsockeye_01_lg  = { name = 'a_c_fishsalmonsockeye_01_lg',  label = 'Salmon Sockeye (L)',   weight = 900,  type = 'item', image = 'a_c_fishsalmonsockeye_01_lg.png',  unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishsalmonsockeye_01_ml  = { name = 'a_c_fishsalmonsockeye_01_ml',  label = 'Salmon Sockeye (ML)',  weight = 800,  type = 'item', image = 'a_c_fishsalmonsockeye_01_ml.png',  unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishsalmonsockeye_01_ms  = { name = 'a_c_fishsalmonsockeye_01_ms',  label = 'Salmon Sockeye (M)',   weight = 600,  type = 'item', image = 'a_c_fishsalmonsockeye_01_ms.png',  unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishsmallmouthbass_01_lg = { name = 'a_c_fishsmallmouthbass_01_lg', label = 'Small Mouth Bass (L)', weight = 900,  type = 'item', image = 'a_c_fishsmallmouthbass_01_lg.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    a_c_fishsmallmouthbass_01_ms = { name = 'a_c_fishsmallmouthbass_01_ms', label = 'Small Mouth Bass (M)', weight = 600,  type = 'item', image = 'a_c_fishsmallmouthbass_01_ms.png', unique = true, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },

    -- fishing bait
    p_baitbread01x   = { name = 'p_baitbread01x',   label = 'Bread Bait',    weight = 10, type = 'item', image = 'p_baitbread01x.png',   unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_baitcorn01x    = { name = 'p_baitcorn01x',    label = 'Corn Bait',     weight = 10, type = 'item', image = 'p_baitcorn01x.png',    unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_baitcheese01x  = { name = 'p_baitcheese01x',  label = 'Cheese Bait',   weight = 10, type = 'item', image = 'p_baitcheese01x.png',  unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_baitworm01x    = { name = 'p_baitworm01x',    label = 'Worm Bait',     weight = 10, type = 'item', image = 'p_baitworm01x.png',    unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_baitcricket01x = { name = 'p_baitcricket01x', label = 'Cricket Bait',  weight = 10, type = 'item', image = 'p_baitcricket01x.png', unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_crawdad01x     = { name = 'p_crawdad01x',     label = 'Crawfish Bait', weight = 10, type = 'item', image = 'p_crawdad01x.png',     unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },

    -- fishing lures
    p_finishedragonfly01x          = { name = 'p_finishedragonfly01x',          label = 'Dragonfly Lure',           weight = 10, type = 'item', image = 'p_finishedragonfly01x.png',          unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_finisdfishlure01x            = { name = 'p_finisdfishlure01x',            label = 'Fish Lure',                weight = 10, type = 'item', image = 'p_finisdfishlure01x.png',            unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_finishdcrawd01x              = { name = 'p_finishdcrawd01x',              label = 'Crawfish Lure',            weight = 10, type = 'item', image = 'p_finishdcrawd01x.png',              unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_finishedragonflylegendary01x = { name = 'p_finishedragonflylegendary01x', label = 'Legendary Dragonfly Lure', weight = 10, type = 'item', image = 'p_finishedragonflylegendary01x.png', unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_finisdfishlurelegendary01x   = { name = 'p_finisdfishlurelegendary01x',   label = 'Legendary Fish Lure',      weight = 10, type = 'item', image = 'p_finisdfishlurelegendary01x.png',   unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_finishdcrawdlegendary01x     = { name = 'p_finishdcrawdlegendary01x',     label = 'Legendary Crawfish Lure',  weight = 10, type = 'item', image = 'p_finishdcrawdlegendary01x.png',     unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_lgoc_spinner_v4              = { name = 'p_lgoc_spinner_v4',              label = 'Spinner',                  weight = 10, type = 'item', image = 'p_lgoc_spinner_v4.png',              unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },
    p_lgoc_spinner_v6              = { name = 'p_lgoc_spinner_v6',              label = 'Improved Spinner',         weight = 10, type = 'item', image = 'p_lgoc_spinner_v6.png',              unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'used for fishing' },

    -----------------------------------------------
    -- WEAPONS
    -----------------------------------------------
    -- customice weapon
    gunsmith = { name = 'gunsmith', label = 'Gun craft', weight = 12000, type = 'item', image = 'guncraft.png', unique = false, useable = true,  shouldClose = true, description = 'Placeholder'},

    -- maintenance
    weapon_repair_kit = { name = 'weapon_repair_kit', label = 'Weapon Repair Kit', weight = 350, type = 'item', image = 'weapon_repair_kit.png', unique = false, useable = true, shouldClose = true, description = 'Used for weapon maintenance' },

    -- revolver
    weapon_revolver_cattleman              = { name = 'weapon_revolver_cattleman',              label = 'Cattleman Revolver',                weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_cattleman.png',              unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_cattleman_mexican      = { name = 'weapon_revolver_cattleman_mexican',      label = 'Cattleman Mexican Revolver',        weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_cattleman_mexican.png',      unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_doubleaction           = { name = 'weapon_revolver_doubleaction',           label = 'Double Action Revolver',            weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_doubleaction.png',           unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_doubleaction_gambler   = { name = 'weapon_revolver_doubleaction_gambler',   label = 'Double Action Gambler Revolver',    weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_doubleaction_gambler.png',   unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_schofield              = { name = 'weapon_revolver_schofield',              label = 'Schofield Revolver',                weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_schofield.png',               unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_lemat                  = { name = 'weapon_revolver_lemat',                  label = 'Lemat Revolver',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_lemat.png',                  unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_navy                   = { name = 'weapon_revolver_navy',                   label = 'Navy Revolver',                     weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_navy.png',                   unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    weapon_revolver_navy_crossover         = { name = 'weapon_revolver_navy_crossover',         label = 'Navy Crossover Revolver',           weight = 1000, type = 'weapon', ammotype = 'AMMO_REVOLVER', image = 'weapon_revolver_navy_crossover.png',         unique = true, useable = true, shouldClose = true, description = 'Takes revolver ammo' },
    -- pistol
    weapon_pistol_volcanic                 = { name = 'weapon_pistol_volcanic',                 label = 'Volcanic Pistol',                   weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_volcanic.png',                 unique = true, useable = true, shouldClose = true, description = 'Takes pistol ammo' },
    weapon_pistol_m1899                    = { name = 'weapon_pistol_m1899',                    label = 'm1899 Pistol',                      weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_m1899.png',                    unique = true, useable = true, shouldClose = true, description = 'Takes pistol ammo' },
    weapon_pistol_mauser                   = { name = 'weapon_pistol_mauser',                   label = 'Mauser Pistol',                     weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_mauser.png',                   unique = true, useable = true, shouldClose = true, description = 'Takes pistol ammo' },
    weapon_pistol_semiauto                 = { name = 'weapon_pistol_semiauto',                 label = 'Semi-Auto Pistol',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL',   image = 'weapon_pistol_semiauto.png',                 unique = true, useable = true, shouldClose = true, description = 'Takes pistol ammo' },
    -- repeater
    weapon_repeater_carbine                = { name = 'weapon_repeater_carbine',                label = 'Carbine Repeater',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_carbine.png',                unique = true, useable = true, shouldClose = true, description = 'Takes repeater ammo' },
    weapon_repeater_winchester             = { name = 'weapon_repeater_winchester',             label = 'Winchester Repeater',               weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_winchester.png',             unique = true, useable = true, shouldClose = true, description = 'Takes repeater ammo' },
    weapon_repeater_henry                  = { name = 'weapon_repeater_henry',                  label = 'Henry Repeater',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_henry.png',                  unique = true, useable = true, shouldClose = true, description = 'Takes repeater ammo' },
    weapon_repeater_evans                  = { name = 'weapon_repeater_evans',                  label = 'Evans Repeater',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_REPEATER', image = 'weapon_repeater_evans.png',                  unique = true, useable = true, shouldClose = true, description = 'Takes repeater ammo' },
    -- rifle
    weapon_rifle_varmint                   = { name = 'weapon_rifle_varmint',                   label = 'Varmint Rifle',                     weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',          image = 'weapon_rifle_varmint.png',             unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    weapon_rifle_springfield               = { name = 'weapon_rifle_springfield',               label = 'Springfield Rifle',                 weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',          image = 'weapon_rifle_springfield.png',         unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    weapon_rifle_boltaction                = { name = 'weapon_rifle_boltaction',                label = 'Boltaction Rifle',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',          image = 'weapon_rifle_boltaction.png',          unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    weapon_rifle_elephant                  = { name = 'weapon_rifle_elephant',                  label = 'Elephant Rifle',                    weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE_ELEPHANT', image = 'weapon_rifle_elephant.png',            unique = true, useable = true, shouldClose = true, description = 'Takes elephant rifle ammo' },
    -- sniperrifle
    weapon_sniperrifle_rollingblock        = { name = 'weapon_sniperrifle_rollingblock',        label = 'Rollingblock Sniper Rifle',         weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_sniperrifle_rollingblock.png',        unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    weapon_sniperrifle_rollingblock_exotic = { name = 'weapon_sniperrifle_rollingblock_exotic', label = 'Rollingblock Exotic Sniper Rifle',  weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_sniperrifle_rollingblock_exotic.png', unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    weapon_sniperrifle_carcano             = { name = 'weapon_sniperrifle_carcano',             label = 'Rollingblock Carcano Sniper Rifle', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE',    image = 'weapon_sniperrifle_carcano.png',             unique = true, useable = true, shouldClose = true, description = 'Takes rifle ammo' },
    -- shotgun
    weapon_shotgun_doublebarrel            = { name = 'weapon_shotgun_doublebarrel',            label = 'Double Barrel Shotgun',             weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_doublebarrel.png',            unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    weapon_shotgun_doublebarrel_exotic     = { name = 'weapon_shotgun_doublebarrel_exotic',     label = 'Double Barrel Exotic Shotgun',      weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_doublebarrel_exotic.png',     unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    weapon_shotgun_sawedoff                = { name = 'weapon_shotgun_sawedoff',                label = 'Sawedoff Shotgun',                  weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_sawedoff.png',                unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    weapon_shotgun_semiauto                = { name = 'weapon_shotgun_semiauto',                label = 'Semi-Auto Shotgun',                 weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_semiauto.png',                unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    weapon_shotgun_pump                    = { name = 'weapon_shotgun_pump',                    label = 'Pump Action Shotgun',               weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_pump.png',                    unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    weapon_shotgun_repeating               = { name = 'weapon_shotgun_repeating',               label = 'Repeating Shotgun',                 weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN',  image = 'weapon_shotgun_repeating.png',               unique = true, useable = true, shouldClose = true, description = 'Takes shotgun ammo' },
    -- bow
    weapon_bow                             = { name = 'weapon_bow',                             label = 'Standard Bow',                      weight = 1000, type = 'weapon', ammotype = 'AMMO_ARROW',    image = 'weapon_bow.png',                             unique = true, useable = true, shouldClose = true, description = 'Takes arrow ammo' },
    weapon_bow_improved                    = { name = 'weapon_bow_improved',                    label = 'Improved Bow',                      weight = 1000, type = 'weapon', ammotype = 'AMMO_ARROW',    image = 'weapon_bow_improved.png',                    unique = true, useable = true, shouldClose = true, description = 'Takes arrow ammo' },
    -- lasso
    weapon_lasso                           = { name = 'weapon_lasso',                           label = 'Standard Lasso',                    weight = 1000, type = 'equipment', ammotype = nil,          image = 'weapon_lasso.png',                           unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_lasso_reinforced                = { name = 'weapon_lasso_reinforced',                label = 'Reinforced Lasso',                  weight = 1000, type = 'equipment', ammotype = nil,          image = 'weapon_lasso_reinforced.png',                unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    -- melee / knife
    weapon_melee_knife                     = { name = 'weapon_melee_knife',                     label = 'Hunting Knife',                     weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_knife.png',                     unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_knife_jawbone             = { name = 'weapon_melee_knife_jawbone',             label = 'Jawbone Knife',                     weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_knife_jawbone.png',             unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_knife_trader              = { name = 'weapon_melee_knife_trader',              label = 'Trader Knife',                      weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_knife_trader.png',              unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_knife_horror              = { name = 'weapon_melee_knife_horror',              label = 'Horror Knife',                      weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_knife_horror.png',              unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_knife_rustic              = { name = 'weapon_melee_knife_rustic',              label = 'Rustic Knife',                      weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_knife_rustic.png',              unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_machete                   = { name = 'weapon_melee_machete',                   label = 'Machete',                           weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_machete.png',                   unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_machete_horror            = { name = 'weapon_melee_machete_horror',            label = 'Machete Horror',                    weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_machete_horror.png',            unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_machete_collector         = { name = 'weapon_melee_machete_collector',         label = 'Machete Collector',                 weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_machete_collector.png',         unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_torch                     = { name = 'weapon_melee_torch',                     label = 'Torch',                             weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_torch.png',                     unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    -- held
    weapon_melee_lantern                   = { name = 'weapon_melee_lantern',                   label = 'Lantern',                           weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_lantern.png',                   unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_davy_lantern              = { name = 'weapon_melee_davy_lantern',              label = 'Davy Lantern',                      weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_davy_lantern.png',              unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_lantern_halloween         = { name = 'weapon_melee_lantern_halloween',         label = 'Halloween Lantern',                 weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_melee_lantern_halloween.png',         unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_kit_binoculars                  = { name = 'weapon_kit_binoculars',                  label = 'Binoculars',                        weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_kit_binoculars.png',                  unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_kit_binoculars_improved         = { name = 'weapon_kit_binoculars_improved',         label = 'Improved Binoculars',               weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_kit_binoculars_improved.png',         unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_kit_camera                      = { name = 'weapon_kit_camera',                      label = 'Camera',                            weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_kit_camera.png',                      unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_kit_camera_advanced             = { name = 'weapon_kit_camera_advanced',             label = 'Advanced Camera',                   weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_kit_camera_advanced.png',             unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_kit_metal_detector              = { name = 'weapon_kit_metal_detector',              label = 'Metal Detector',                    weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_kit_metal_detector.png',              unique = true, useable = true, shouldClose = true, description = 'Placeholder' },
    -- trown
    weapon_melee_hatchet                   = { name = 'weapon_melee_hatchet',                   label = 'Hatchet',                           weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_melee_hatchet.png',                   unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_hatchet_hunter            = { name = 'weapon_melee_hatchet_hunter',            label = 'Hunter Hatchet',                    weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_melee_hatchet_hunter.png',            unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_molotov                  = { name = 'weapon_thrown_molotov',                  label = 'Molotov',                           weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_molotov.png',                  unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_tomahawk                 = { name = 'weapon_thrown_tomahawk',                 label = 'Tomahawk',                          weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_tomahawk.png',                 unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_tomahawk_ancient         = { name = 'weapon_thrown_tomahawk_ancient',         label = 'Tomahawk Ancient',                  weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_tomahawk_ancient.png',         unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_dynamite                 = { name = 'weapon_thrown_dynamite',                 label = 'Dynamite',                          weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_dynamite.png',                 unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_poisonbottle             = { name = 'weapon_thrown_poisonbottle',             label = 'Poison Bottle',                     weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_poisonbottle.png',             unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_throwing_knives          = { name = 'weapon_thrown_throwing_knives',          label = 'Throwing Knives',                   weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_throwing_knives.png',          unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_melee_cleaver                   = { name = 'weapon_melee_cleaver',                   label = 'Cleaver',                           weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_melee_cleaver.png',                   unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_bolas                    = { name = 'weapon_thrown_bolas',                    label = 'Bolas',                             weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_bolas.png',                    unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_bolas_hawkmoth           = { name = 'weapon_thrown_bolas_hawkmoth',           label = 'Hawkmoth Bolas',                    weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_bolas_hawkmoth.png',           unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_bolas_ironspiked         = { name = 'weapon_thrown_bolas_ironspiked',         label = 'Iron Spiked Bolas',                 weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_bolas_ironspiked.png',         unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    weapon_thrown_bolas_intertwined        = { name = 'weapon_thrown_bolas_intertwined',        label = 'Intertwined Bolas',                 weight = 1000, type = 'weapon_thrown', ammotype = nil,     image = 'weapon_thrown_bolas_intertwined.png',        unique = false, useable = true, shouldClose = true, description = 'Placeholder' },
    -- fishing
    weapon_fishingrod                      = { name = 'weapon_fishingrod',                      label = 'Fishing Rod',                       weight = 1000, type = 'equipment', ammotype = nil,         image = 'weapon_fishingrod.png',                      unique = true, useable = true, shouldClose = true, description = 'Placeholder' },

    -----------------------------------------------
    -- AMMO
    -----------------------------------------------

    -- revolver
    ammo_revolver            = { name = 'ammo_revolver',            label = 'Revolver Ammo (N)',  weight = 100, type = 'item', image = 'ammo_revolver.png',            unique = false, useable = true, shouldClose = true, description = 'Standard Revolver Ammo' },
    ammo_revolver_express    = { name = 'ammo_revolver_express',    label = 'Revolver Ammo (E)',  weight = 100, type = 'item', image = 'ammo_revolver_express.png',    unique = false, useable = true, shouldClose = true, description = 'Express Revolver Ammo' },
    ammo_revolver_explosive  = { name = 'ammo_revolver_explosive',  label = 'Revolver Ammo (EE)', weight = 100, type = 'item', image = 'ammo_revolver_explosive.png',  unique = false, useable = true, shouldClose = true, description = 'Explosive Revolver Ammo' },
    ammo_revolver_velocity   = { name = 'ammo_revolver_velocity',   label = 'Revolver Ammo (HV)', weight = 100, type = 'item', image = 'ammo_revolver_velocity.png',   unique = false, useable = true, shouldClose = true, description = 'High Velocity Revolver Ammo' },
    ammo_revolver_splitpoint = { name = 'ammo_revolver_splitpoint', label = 'Revolver Ammo (SP)', weight = 100, type = 'item', image = 'ammo_revolver_splitpoint.png', unique = false, useable = true, shouldClose = true, description = 'Split Point Revolver Ammo' },

    -- pistol
    ammo_pistol            = { name = 'ammo_pistol',            label = 'Pistol Ammo (N)',  weight = 100, type = 'item', image = 'ammo_pistol.png',            unique = false, useable = true, shouldClose = true, description = 'Standard Pistol Ammo' },
    ammo_pistol_express    = { name = 'ammo_pistol_express',    label = 'Pistol Ammo (E)',  weight = 100, type = 'item', image = 'ammo_pistol_express.png',    unique = false, useable = true, shouldClose = true, description = 'Express Pistol Ammo' },
    ammo_pistol_explosive  = { name = 'ammo_pistol_explosive',  label = 'Pistol Ammo (EE)', weight = 100, type = 'item', image = 'ammo_pistol_explosive.png',  unique = false, useable = true, shouldClose = true, description = 'Explosive Pistol Ammo' },
    ammo_pistol_velocity   = { name = 'ammo_pistol_velocity',   label = 'Pistol Ammo (HV)', weight = 100, type = 'item', image = 'ammo_pistol_velocity.png',   unique = false, useable = true, shouldClose = true, description = 'High Velocity Pistol Ammo' },
    ammo_pistol_splitpoint = { name = 'ammo_pistol_splitpoint', label = 'Pistol Ammo (SP)', weight = 100, type = 'item', image = 'ammo_pistol_splitpoint.png', unique = false, useable = true, shouldClose = true, description = 'Split Point Pistol Ammo' },

    -- repeater
    ammo_repeater            = { name = 'ammo_repeater',            label = 'Repeater Ammo (N)',  weight = 100, type = 'item', image = 'ammo_repeater.png',            unique = false, useable = true, shouldClose = true, description = 'Standard Repeater Ammo' },
    ammo_repeater_express    = { name = 'ammo_repeater_express',    label = 'Repeater Ammo (E)',  weight = 100, type = 'item', image = 'ammo_repeater_express.png',    unique = false, useable = true, shouldClose = true, description = 'Express Repeater Ammo' },
    ammo_repeater_explosive  = { name = 'ammo_repeater_explosive',  label = 'Repeater Ammo (EE)', weight = 100, type = 'item', image = 'ammo_repeater_explosive.png',  unique = false, useable = true, shouldClose = true, description = 'Explosive Repeater Ammo' },
    ammo_repeater_velocity   = { name = 'ammo_repeater_velocity',   label = 'Repeater Ammo (HV)', weight = 100, type = 'item', image = 'ammo_repeater_velocity.png',   unique = false, useable = true, shouldClose = true, description = 'High Velocity Repeater Ammo' },
    ammo_repeater_splitpoint = { name = 'ammo_repeater_splitpoint', label = 'Repeater Ammo (SP)', weight = 100, type = 'item', image = 'ammo_repeater_splitpoint.png', unique = false, useable = true, shouldClose = true, description = 'Split Point Repeater Ammo' },

    -- rifle
    ammo_rifle            = { name = 'ammo_rifle',            label = 'Rifle Ammo (N)',  weight = 100, type = 'item', image = 'ammo_rifle.png',            unique = false, useable = true, shouldClose = true, description = 'Standard Rifle Ammo' },
    ammo_rifle_express    = { name = 'ammo_rifle_express',    label = 'Rifle Ammo (E)',  weight = 100, type = 'item', image = 'ammo_rifle_express.png',    unique = false, useable = true, shouldClose = true, description = 'Express Rifle Ammo' },
    ammo_rifle_explosive  = { name = 'ammo_rifle_explosive',  label = 'Rifle Ammo (EE)', weight = 100, type = 'item', image = 'ammo_rifle_explosive.png',  unique = false, useable = true, shouldClose = true, description = 'Explosive Rifle Ammo' },
    ammo_rifle_velocity   = { name = 'ammo_rifle_velocity',   label = 'Rifle Ammo (HV)', weight = 100, type = 'item', image = 'ammo_rifle_velocity.png',   unique = false, useable = true, shouldClose = true, description = 'High Velocity Rifle Ammo' },
    ammo_rifle_splitpoint = { name = 'ammo_rifle_splitpoint', label = 'Rifle Ammo (SP)', weight = 100, type = 'item', image = 'ammo_rifle_splitpoint.png', unique = false, useable = true, shouldClose = true, description = 'Split Point Rifle Ammo' },

    -- shotgun
    ammo_shotgun                     = { name = 'ammo_shotgun',                     label = 'Shotgun Ammo (N)',  weight = 100, type = 'item', image = 'ammo_shotgun.png',                     unique = false, useable = true, shouldClose = true, description = 'Standard Shotgun Buckshot' },
    ammo_shotgun_buckshot_incendiary = { name = 'ammo_shotgun_buckshot_incendiary', label = 'Shotgun Ammo (BI)', weight = 100, type = 'item', image = 'ammo_shotgun_buckshot_incendiary.png', unique = false, useable = true, shouldClose = true, description = 'Incendiary Shotgun Buckshot' },
    ammo_shotgun_slug                = { name = 'ammo_shotgun_slug',                label = 'Shotgun Ammo (S)',  weight = 100, type = 'item', image = 'ammo_shotgun_slug.png',                unique = false, useable = true, shouldClose = true, description = 'Shotgun Slug Ammo' },
    ammo_shotgun_slug_explosive      = { name = 'ammo_shotgun_slug_explosive',      label = 'Shotgun Ammo (SE)', weight = 100, type = 'item', image = 'ammo_shotgun_slug_explosive.png',      unique = false, useable = true, shouldClose = true, description = 'Explosive Shotgun Slug Ammo' },

    -- elephant rifle
    ammo_rifle_elephant = { name = 'ammo_rifle_elephant', label = 'Elephant Rifle Ammo (N)', weight = 100, type = 'item', image = 'ammo_rifle_elephant.png', unique = false, useable = true, shouldClose = true, description = 'Elephant Rifle Ammo' },

    -- varmint rifle
    ammo_varmint              = { name = 'ammo_varmint',              label = 'Varmint Ammo (N)',  weight = 100, type = 'item', image = 'ammo_varmint.png',              unique = false, useable = true, shouldClose = true, description = 'Standard Varmint Rifle Ammo' },
    ammo_varmint_tranquilizer = { name = 'ammo_varmint_tranquilizer', label = 'Varmint Ammo (T)',  weight = 100, type = 'item', image = 'ammo_varmint_tranquilizer.png', unique = false, useable = true, shouldClose = true, description = 'Varmint Rifle Tranquilizer Ammo' },

    -- arrows
    ammo_arrow          = { name = 'ammo_arrow',          label = 'Arrow (N)',  weight = 200, type = 'item', image = 'ammo_arrow.png',          unique = false, useable = true, shouldClose = true, description = 'Standard Arrow' },
    ammo_arrow_small    = { name = 'ammo_arrow_small',    label = 'Arrow (SG)', weight = 200, type = 'item', image = 'ammo_arrow_small.png',    unique = false, useable = true, shouldClose = true, description = 'Small Game Arrow' },
    ammo_arrow_improved = { name = 'ammo_arrow_improved', label = 'Arrow (I)',  weight = 200, type = 'item', image = 'ammo_arrow_improved.png', unique = false, useable = true, shouldClose = true, description = 'Improved Arrow' },
    ammo_arrow_fire     = { name = 'ammo_arrow_fire',     label = 'Arrow (F)',  weight = 200, type = 'item', image = 'ammo_arrow_fire.png',     unique = false, useable = true, shouldClose = true, description = 'Fire Arrow' },
    ammo_arrow_poison   = { name = 'ammo_arrow_poison',   label = 'Arrow (P)',  weight = 200, type = 'item', image = 'ammo_arrow_poison.png',   unique = false, useable = true, shouldClose = true, description = 'Poison Arrow' },
    ammo_arrow_dynamite = { name = 'ammo_arrow_dynamite', label = 'Arrow (D)',  weight = 200, type = 'item', image = 'ammo_arrow_dynamite.png', unique = false, useable = true, shouldClose = true, description = 'Dynamite Arrow' },

    --- Consumeables
    bread_roll = { name = 'bread_roll', label = 'Bread Roll', weight = 120, type = 'item', image = 'bread_roll.png', unique = false, useable = true, decay = 240, delete = true, shouldClose = true, description = 'A fresh baked bread roll.' },
    cornbread = { name = 'cornbread', label = 'Cornbread', weight = 140, type = 'item', image = 'cornbread.png', unique = false, useable = true, decay = 220, delete = true, shouldClose = true, description = 'Dense skillet cornbread with a crisp edge.' },
    biscuits = { name = 'biscuits', label = 'Buttermilk Biscuits', weight = 130, type = 'item', image = 'biscuits.png', unique = false, useable = true, decay = 210, delete = true, shouldClose = true, description = 'A pair of soft buttermilk biscuits.' },
    cooked_beef = { name = 'cooked_beef', label = 'Cooked Beef', weight = 220, type = 'item', image = 'cooked_beef.png', unique = false, useable = true, decay = 150, delete = true, shouldClose = true, description = 'A hearty serving of cooked beef.' },
    venison_steak = { name = 'venison_steak', label = 'Venison Steak', weight = 220, type = 'item', image = 'venison_steak.png', unique = false, useable = true, decay = 150, delete = true, shouldClose = true, description = 'A lean steak cut from wild venison.' },
    cooked_pork = { name = 'cooked_pork', label = 'Cooked Pork', weight = 215, type = 'item', image = 'cooked_pork.png', unique = false, useable = true, decay = 145, delete = true, shouldClose = true, description = 'A thick slice of seasoned pork.' },
    roast_chicken = { name = 'roast_chicken', label = 'Roast Chicken', weight = 200, type = 'item', image = 'roast_chicken.png', unique = false, useable = true, decay = 140, delete = true, shouldClose = true, description = 'Roasted chicken with crisp skin.' },
    cooked_rabbit = { name = 'cooked_rabbit', label = 'Cooked Rabbit', weight = 190, type = 'item', image = 'cooked_rabbit.png', unique = false, useable = true, decay = 140, delete = true, shouldClose = true, description = 'Tender rabbit cooked over a campfire.' },
    cooked_trout = { name = 'cooked_trout', label = 'Cooked Trout', weight = 180, type = 'item', image = 'cooked_trout.png', unique = false, useable = true, decay = 120, delete = true, shouldClose = true, description = 'Fresh trout cooked until flaky.' },
    beef_stew = { name = 'beef_stew', label = 'Beef Stew', weight = 320, type = 'item', image = 'beef_stew.png', unique = false, useable = true, decay = 90, delete = true, shouldClose = true, description = 'A hot bowl of beef and root vegetable stew.' },
    vegetable_stew = { name = 'vegetable_stew', label = 'Vegetable Stew', weight = 300, type = 'item', image = 'vegetable_stew.png', unique = false, useable = true, decay = 90, delete = true, shouldClose = true, description = 'A warm stew packed with garden vegetables.' },
    baked_beans = { name = 'baked_beans', label = 'Baked Beans', weight = 240, type = 'item', image = 'baked_beans.png', unique = false, useable = true, decay = 360, delete = true, shouldClose = true, description = 'Sweet and smoky baked beans from a tin.' },
    canned_peaches = { name = 'canned_peaches', label = 'Canned Peaches', weight = 230, type = 'item', image = 'canned_peaches.png', unique = false, useable = true, decay = 420, delete = true, shouldClose = true, description = 'Sweet peach slices packed in syrup.' },
    canned_corn = { name = 'canned_corn', label = 'Canned Corn', weight = 230, type = 'item', image = 'canned_corn.png', unique = false, useable = true, decay = 420, delete = true, shouldClose = true, description = 'Tender corn sealed in a sturdy tin.' },
    apple = { name = 'apple', label = 'Red Apple', weight = 90, type = 'item', image = 'apple.png', unique = false, useable = true, decay = 100, delete = true, shouldClose = true, description = 'A crisp red apple.' },
    pear = { name = 'pear', label = 'Ripe Pear', weight = 90, type = 'item', image = 'pear.png', unique = false, useable = true, decay = 100, delete = true, shouldClose = true, description = 'A soft and juicy ripe pear.' },
    peach = { name = 'peach', label = 'Fresh Peach', weight = 85, type = 'item', image = 'peach.png', unique = false, useable = true, decay = 90, delete = true, shouldClose = true, description = 'A fragrant peach with sweet flesh.' },
    chocolate_bar = { name = 'chocolate_bar', label = 'Chocolate Bar', weight = 80, type = 'item', image = 'chocolate_bar.png', unique = false, useable = true, decay = 500, delete = true, shouldClose = true, description = 'A wrapped bar of rich dark chocolate.' },
    clean_water = { name = 'clean_water', label = 'Clean Water', weight = 250, type = 'item', image = 'clean_water.png', unique = false, useable = true, delete = true, shouldClose = true, description = 'A canteen filled with clean drinking water.' },
    camp_coffee = { name = 'camp_coffee', label = 'Camp Coffee', weight = 160, type = 'item', image = 'camp_coffee.png', unique = false, useable = true, decay = 45, delete = true, shouldClose = true, description = 'Strong black coffee brewed over the fire.' },
    black_tea = { name = 'black_tea', label = 'Black Tea', weight = 150, type = 'item', image = 'black_tea.png', unique = false, useable = true, decay = 45, delete = true, shouldClose = true, description = 'A warm cup of strong black tea.' },
    fresh_milk = { name = 'fresh_milk', label = 'Fresh Milk', weight = 260, type = 'item', image = 'fresh_milk.png', unique = false, useable = true, decay = 60, delete = true, shouldClose = true, description = 'A bottle of fresh whole milk.' },
    lemonade = { name = 'lemonade', label = 'Lemonade', weight = 240, type = 'item', image = 'lemonade.png', unique = false, useable = true, decay = 120, delete = true, shouldClose = true, description = 'Sweet lemonade with a sharp citrus bite.' },
    sarsaparilla = { name = 'sarsaparilla', label = 'Sarsaparilla', weight = 250, type = 'item', image = 'sarsaparilla.png', unique = false, useable = true, decay = 240, delete = true, shouldClose = true, description = 'A sweet bottle of frontier sarsaparilla.' },
    berry_juice = { name = 'berry_juice', label = 'Berry Juice', weight = 240, type = 'item', image = 'berry_juice.png', unique = false, useable = true, decay = 100, delete = true, shouldClose = true, description = 'Juice pressed from ripe wild berries.' },
    lager_beer = { name = 'lager_beer', label = 'Lager Beer', weight = 260, type = 'item', image = 'lager_beer.png', unique = false, useable = true, decay = 300, delete = true, shouldClose = true, description = 'A cold bottle of crisp lager beer.' },
    kentucky_whiskey = { name = 'kentucky_whiskey', label = 'Kentucky Whiskey', weight = 280, type = 'item', image = 'kentucky_whiskey.png', unique = false, useable = true, delete = true, shouldClose = true, description = 'A strong bottle of Kentucky whiskey.' },
    fine_brandy = { name = 'fine_brandy', label = 'Fine Brandy', weight = 270, type = 'item', image = 'fine_brandy.png', unique = false, useable = true, delete = true, shouldClose = true, description = 'A smooth bottle of aged fine brandy.' },
    moonshine = { name = 'moonshine', label = 'Moonshine', weight = 300, type = 'item', image = 'moonshine.png', unique = false, useable = true, delete = true, shouldClose = true, description = 'Powerful clear liquor from an unmarked jug.' },
    dark_rum = { name = 'dark_rum', label = 'Dark Rum', weight = 280, type = 'item', image = 'dark_rum.png', unique = false, useable = true, delete = true, shouldClose = true, description = 'Dark spiced rum with a heavy finish.' },

    -- Lockpick Item For Doorlock Script
    lockpick = { name = 'lockpick', label = 'Lockpick', weight = 100, type = 'item', image = 'lockpick.png', unique = false, useable = true, shouldClose = true, description = 'A worn set of tools used to work stubborn locks.' },

        -- additional pelts and hides
    medium_pelt       = { name = 'medium_pelt',       label = 'Medium Pelt',       weight = 100, type = 'item', image = 'medium_pelt.png',       unique = false, useable = true, shouldClose = true, description = 'Medium-sized animal pelt' },
    large_pelt        = { name = 'large_pelt',        label = 'Large Pelt',        weight = 100, type = 'item', image = 'large_pelt.png',        unique = false, useable = true, shouldClose = true, description = 'Large animal pelt' },
    animal_hide       = { name = 'animal_hide',       label = 'Animal Hide',       weight = 100, type = 'item', image = 'animal_hide.png',       unique = false, useable = true, shouldClose = true, description = 'Untreated animal hide' },
    deer_hide         = { name = 'deer_hide',         label = 'Deer Hide',         weight = 100, type = 'item', image = 'deer_hide.png',         unique = false, useable = true, shouldClose = true, description = 'Hide taken from a deer' },
    elk_hide          = { name = 'elk_hide',          label = 'Elk Hide',          weight = 100, type = 'item', image = 'elk_hide.png',          unique = false, useable = true, shouldClose = true, description = 'Hide taken from an elk' },
    moose_hide        = { name = 'moose_hide',        label = 'Moose Hide',        weight = 100, type = 'item', image = 'moose_hide.png',        unique = false, useable = true, shouldClose = true, description = 'Heavy hide taken from a moose' },
    pronghorn_hide    = { name = 'pronghorn_hide',    label = 'Pronghorn Hide',    weight = 100, type = 'item', image = 'pronghorn_hide.png',    unique = false, useable = true, shouldClose = true, description = 'Hide taken from a pronghorn' },
    bison_hide        = { name = 'bison_hide',        label = 'Bison Hide',        weight = 100, type = 'item', image = 'bison_hide.png',        unique = false, useable = true, shouldClose = true, description = 'Thick hide taken from a bison' },
    bear_hide         = { name = 'bear_hide',         label = 'Bear Hide',         weight = 100, type = 'item', image = 'bear_hide.png',         unique = false, useable = true, shouldClose = true, description = 'Heavy hide taken from a bear' },
    wolf_pelt         = { name = 'wolf_pelt',         label = 'Wolf Pelt',         weight = 100, type = 'item', image = 'wolf_pelt.png',         unique = false, useable = true, shouldClose = true, description = 'Pelt taken from a wolf' },
    coyote_pelt       = { name = 'coyote_pelt',       label = 'Coyote Pelt',       weight = 100, type = 'item', image = 'coyote_pelt.png',       unique = false, useable = true, shouldClose = true, description = 'Pelt taken from a coyote' },
    fox_pelt          = { name = 'fox_pelt',          label = 'Fox Pelt',          weight = 100, type = 'item', image = 'fox_pelt.png',          unique = false, useable = true, shouldClose = true, description = 'Pelt taken from a fox' },
    cougar_pelt       = { name = 'cougar_pelt',       label = 'Cougar Pelt',       weight = 100, type = 'item', image = 'cougar_pelt.png',       unique = false, useable = true, shouldClose = true, description = 'Pelt taken from a cougar' },
    panther_pelt      = { name = 'panther_pelt',      label = 'Panther Pelt',      weight = 100, type = 'item', image = 'panther_pelt.png',      unique = false, useable = true, shouldClose = true, description = 'Rare pelt taken from a panther' },
    boar_hide         = { name = 'boar_hide',         label = 'Boar Hide',         weight = 100, type = 'item', image = 'boar_hide.png',         unique = false, useable = true, shouldClose = true, description = 'Tough hide taken from a boar' },
    alligator_skin    = { name = 'alligator_skin',    label = 'Alligator Skin',    weight = 100, type = 'item', image = 'alligator_skin.png',    unique = false, useable = true, shouldClose = true, description = 'Thick skin taken from an alligator' },

    -- raw hunting meat
    raw_game_meat     = { name = 'raw_game_meat',     label = 'Raw Game Meat',     weight = 100, type = 'item', image = 'raw_game_meat.png',     unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw meat harvested from game' },
    raw_big_game_meat = { name = 'raw_big_game_meat', label = 'Raw Big Game Meat', weight = 100, type = 'item', image = 'raw_big_game_meat.png', unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw meat harvested from large game' },
    raw_venison       = { name = 'raw_venison',       label = 'Raw Venison',       weight = 100, type = 'item', image = 'raw_venison.png',       unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw venison harvested from deer' },
    raw_mutton        = { name = 'raw_mutton',        label = 'Raw Mutton',        weight = 100, type = 'item', image = 'raw_mutton.png',        unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw mutton harvested from sheep or goats' },
    raw_pork          = { name = 'raw_pork',          label = 'Raw Pork',          weight = 100, type = 'item', image = 'raw_pork.png',          unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw pork harvested from boar' },
    raw_bird_meat     = { name = 'raw_bird_meat',     label = 'Raw Bird Meat',     weight = 100, type = 'item', image = 'raw_bird_meat.png',     unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw meat harvested from a bird' },
    raw_rabbit_meat   = { name = 'raw_rabbit_meat',   label = 'Raw Rabbit Meat',   weight = 100, type = 'item', image = 'raw_rabbit_meat.png',   unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw meat harvested from a rabbit' },
    raw_reptile_meat  = { name = 'raw_reptile_meat',  label = 'Raw Reptile Meat',  weight = 100, type = 'item', image = 'raw_reptile_meat.png',  unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw meat harvested from a reptile' },

    -- animal organs and crafting materials
    animal_liver      = { name = 'animal_liver',      label = 'Animal Liver',      weight = 100, type = 'item', image = 'animal_liver.png',      unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Fresh animal liver' },
    animal_kidney     = { name = 'animal_kidney',     label = 'Animal Kidney',     weight = 100, type = 'item', image = 'animal_kidney.png',     unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Fresh animal kidney' },
    animal_fat        = { name = 'animal_fat',        label = 'Animal Fat',        weight = 100, type = 'item', image = 'animal_fat.png',        unique = false, useable = true, shouldClose = true, description = 'Rendered animal fat used for cooking and crafting' },
    animal_bone       = { name = 'animal_bone',       label = 'Animal Bone',       weight = 100, type = 'item', image = 'animal_bone.png',       unique = false, useable = true, shouldClose = true, description = 'Animal bone used for crafting' },
    animal_sinew      = { name = 'animal_sinew',      label = 'Animal Sinew',      weight = 100, type = 'item', image = 'animal_sinew.png',      unique = false, useable = true, shouldClose = true, description = 'Strong animal sinew used for crafting' },
    animal_tooth      = { name = 'animal_tooth',      label = 'Animal Tooth',      weight = 100, type = 'item', image = 'animal_tooth.png',      unique = false, useable = true, shouldClose = true, description = 'Animal tooth used as a crafting material' },
    animal_fang       = { name = 'animal_fang',       label = 'Animal Fang',       weight = 100, type = 'item', image = 'animal_fang.png',       unique = false, useable = true, shouldClose = true, description = 'Sharp fang taken from a predator' },
    animal_claw       = { name = 'animal_claw',       label = 'Animal Claw',       weight = 100, type = 'item', image = 'animal_claw.png',       unique = false, useable = true, shouldClose = true, description = 'Sharp animal claw' },
    animal_horn       = { name = 'animal_horn',       label = 'Animal Horn',       weight = 100, type = 'item', image = 'animal_horn.png',       unique = false, useable = true, shouldClose = true, description = 'Horn taken from a hunted animal' },
    animal_antler     = { name = 'animal_antler',     label = 'Animal Antler',     weight = 100, type = 'item', image = 'animal_antler.png',     unique = false, useable = true, shouldClose = true, description = 'Antler taken from a deer, elk, or moose' },
    animal_tusk       = { name = 'animal_tusk',       label = 'Animal Tusk',       weight = 100, type = 'item', image = 'animal_tusk.png',       unique = false, useable = true, shouldClose = true, description = 'Tusk taken from a large animal' },
    animal_hoof       = { name = 'animal_hoof',       label = 'Animal Hoof',       weight = 100, type = 'item', image = 'animal_hoof.png',       unique = false, useable = true, shouldClose = true, description = 'Hoof taken from a hunted animal' },
    animal_tail       = { name = 'animal_tail',       label = 'Animal Tail',       weight = 100, type = 'item', image = 'animal_tail.png',       unique = false, useable = true, shouldClose = true, description = 'Tail taken from a hunted animal' },
    animal_eye        = { name = 'animal_eye',        label = 'Animal Eye',        weight = 100, type = 'item', image = 'animal_eye.png',        unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Preserved eye taken from a hunted animal' },

    -- bird materials
    flight_feather    = { name = 'flight_feather',    label = 'Flight Feather',    weight = 100, type = 'item', image = 'flight_feather.png',    unique = false, useable = true, shouldClose = true, description = 'Strong feather suitable for crafting arrows' },
    eagle_feather     = { name = 'eagle_feather',     label = 'Eagle Feather',     weight = 100, type = 'item', image = 'eagle_feather.png',     unique = false, useable = true, shouldClose = true, description = 'Rare feather taken from an eagle' },
    hawk_feather      = { name = 'hawk_feather',      label = 'Hawk Feather',      weight = 100, type = 'item', image = 'hawk_feather.png',      unique = false, useable = true, shouldClose = true, description = 'Feather taken from a hawk' },
    owl_feather       = { name = 'owl_feather',       label = 'Owl Feather',       weight = 100, type = 'item', image = 'owl_feather.png',       unique = false, useable = true, shouldClose = true, description = 'Feather taken from an owl' },
    vulture_feather   = { name = 'vulture_feather',   label = 'Vulture Feather',   weight = 100, type = 'item', image = 'vulture_feather.png',   unique = false, useable = true, shouldClose = true, description = 'Feather taken from a vulture' },
    turkey_feather    = { name = 'turkey_feather',    label = 'Turkey Feather',    weight = 100, type = 'item', image = 'turkey_feather.png',    unique = false, useable = true, shouldClose = true, description = 'Feather taken from a wild turkey' },
    bird_beak         = { name = 'bird_beak',         label = 'Bird Beak',         weight = 100, type = 'item', image = 'bird_beak.png',         unique = false, useable = true, shouldClose = true, description = 'Beak taken from a hunted bird' },

    -- harvested carcasses
    animal_carcass    = { name = 'animal_carcass',    label = 'Animal Carcass',    weight = 100, type = 'item', image = 'animal_carcass.png',    unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Unprocessed animal carcass' },
    small_game_carcass = { name = 'small_game_carcass', label = 'Small Game Carcass', weight = 100, type = 'item', image = 'small_game_carcass.png', unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Unprocessed small-game carcass' },
    bird_carcass      = { name = 'bird_carcass',      label = 'Bird Carcass',      weight = 100, type = 'item', image = 'bird_carcass.png',      unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Unprocessed bird carcass' },
    rabbit_carcass    = { name = 'rabbit_carcass',    label = 'Rabbit Carcass',    weight = 100, type = 'item', image = 'rabbit_carcass.png',    unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Unprocessed rabbit carcass' },
    

    ---- Node 7 Horse Reviver pellant!
    horse_reviver = { name = 'horse_reviver', label = 'Horse Reviver Pellant', weight = 100, type = 'item', image = 'horse_reviver.png', unique = false, useable = true, shouldClose = true, description = 'Given to horses' },
    
    
    ---- Hunting Node7
    medium_pelt       = { name = 'medium_pelt',       label = 'Medium Pelt',       weight = 100, type = 'item', image = 'medium_pelt.png',       unique = false, useable = true, shouldClose = true, description = 'Medium-sized animal pelt' },
    large_pelt        = { name = 'large_pelt',        label = 'Large Pelt',        weight = 100, type = 'item', image = 'large_pelt.png',        unique = false, useable = true, shouldClose = true, description = 'Large animal pelt' },
    animal_hide       = { name = 'animal_hide',       label = 'Animal Hide',       weight = 100, type = 'item', image = 'animal_hide.png',       unique = false, useable = true, shouldClose = true, description = 'Untreated animal hide' },
    deer_hide         = { name = 'deer_hide',         label = 'Deer Hide',         weight = 100, type = 'item', image = 'deer_hide.png',         unique = false, useable = true, shouldClose = true, description = 'Hide taken from a deer' },
    elk_hide          = { name = 'elk_hide',          label = 'Elk Hide',          weight = 100, type = 'item', image = 'elk_hide.png',          unique = false, useable = true, shouldClose = true, description = 'Hide taken from an elk' },
    moose_hide        = { name = 'moose_hide',        label = 'Moose Hide',        weight = 100, type = 'item', image = 'moose_hide.png',        unique = false, useable = true, shouldClose = true, description = 'Heavy hide taken from a moose' },
    pronghorn_hide    = { name = 'pronghorn_hide',    label = 'Pronghorn Hide',    weight = 100, type = 'item', image = 'pronghorn_hide.png',    unique = false, useable = true, shouldClose = true, description = 'Hide taken from a pronghorn' },
    bison_hide        = { name = 'bison_hide',        label = 'Bison Hide',        weight = 100, type = 'item', image = 'bison_hide.png',        unique = false, useable = true, shouldClose = true, description = 'Thick hide taken from a bison' },
    bear_hide         = { name = 'bear_hide',         label = 'Bear Hide',         weight = 100, type = 'item', image = 'bear_hide.png',         unique = false, useable = true, shouldClose = true, description = 'Heavy hide taken from a bear' },
    wolf_pelt         = { name = 'wolf_pelt',         label = 'Wolf Pelt',         weight = 100, type = 'item', image = 'wolf_pelt.png',         unique = false, useable = true, shouldClose = true, description = 'Pelt taken from a wolf' },
    coyote_pelt       = { name = 'coyote_pelt',       label = 'Coyote Pelt',       weight = 100, type = 'item', image = 'coyote_pelt.png',       unique = false, useable = true, shouldClose = true, description = 'Pelt taken from a coyote' },
    fox_pelt          = { name = 'fox_pelt',          label = 'Fox Pelt',          weight = 100, type = 'item', image = 'fox_pelt.png',          unique = false, useable = true, shouldClose = true, description = 'Pelt taken from a fox' },
    cougar_pelt       = { name = 'cougar_pelt',       label = 'Cougar Pelt',       weight = 100, type = 'item', image = 'cougar_pelt.png',       unique = false, useable = true, shouldClose = true, description = 'Pelt taken from a cougar' },
    panther_pelt      = { name = 'panther_pelt',      label = 'Panther Pelt',      weight = 100, type = 'item', image = 'panther_pelt.png',      unique = false, useable = true, shouldClose = true, description = 'Rare pelt taken from a panther' },
    boar_hide         = { name = 'boar_hide',         label = 'Boar Hide',         weight = 100, type = 'item', image = 'boar_hide.png',         unique = false, useable = true, shouldClose = true, description = 'Tough hide taken from a boar' },
    alligator_skin    = { name = 'alligator_skin',    label = 'Alligator Skin',    weight = 100, type = 'item', image = 'alligator_skin.png',    unique = false, useable = true, shouldClose = true, description = 'Thick skin taken from an alligator' },

    -- raw hunting meat
    raw_game_meat     = { name = 'raw_game_meat',     label = 'Raw Game Meat',     weight = 100, type = 'item', image = 'raw_game_meat.png',     unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw meat harvested from game' },
    raw_big_game_meat = { name = 'raw_big_game_meat', label = 'Raw Big Game Meat', weight = 100, type = 'item', image = 'raw_big_game_meat.png', unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw meat harvested from large game' },
    raw_venison       = { name = 'raw_venison',       label = 'Raw Venison',       weight = 100, type = 'item', image = 'raw_venison.png',       unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw venison harvested from deer' },
    raw_mutton        = { name = 'raw_mutton',        label = 'Raw Mutton',        weight = 100, type = 'item', image = 'raw_mutton.png',        unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw mutton harvested from sheep or goats' },
    raw_pork          = { name = 'raw_pork',          label = 'Raw Pork',          weight = 100, type = 'item', image = 'raw_pork.png',          unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw pork harvested from boar' },
    raw_bird_meat     = { name = 'raw_bird_meat',     label = 'Raw Bird Meat',     weight = 100, type = 'item', image = 'raw_bird_meat.png',     unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw meat harvested from a bird' },
    raw_rabbit_meat   = { name = 'raw_rabbit_meat',   label = 'Raw Rabbit Meat',   weight = 100, type = 'item', image = 'raw_rabbit_meat.png',   unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw meat harvested from a rabbit' },
    raw_reptile_meat  = { name = 'raw_reptile_meat',  label = 'Raw Reptile Meat',  weight = 100, type = 'item', image = 'raw_reptile_meat.png',  unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Raw meat harvested from a reptile' },

    -- animal organs and crafting materials
    animal_liver      = { name = 'animal_liver',      label = 'Animal Liver',      weight = 100, type = 'item', image = 'animal_liver.png',      unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Fresh animal liver' },
    animal_kidney     = { name = 'animal_kidney',     label = 'Animal Kidney',     weight = 100, type = 'item', image = 'animal_kidney.png',     unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Fresh animal kidney' },
    animal_fat        = { name = 'animal_fat',        label = 'Animal Fat',        weight = 100, type = 'item', image = 'animal_fat.png',        unique = false, useable = true, shouldClose = true, description = 'Rendered animal fat used for cooking and crafting' },
    animal_bone       = { name = 'animal_bone',       label = 'Animal Bone',       weight = 100, type = 'item', image = 'animal_bone.png',       unique = false, useable = true, shouldClose = true, description = 'Animal bone used for crafting' },
    animal_sinew      = { name = 'animal_sinew',      label = 'Animal Sinew',      weight = 100, type = 'item', image = 'animal_sinew.png',      unique = false, useable = true, shouldClose = true, description = 'Strong animal sinew used for crafting' },
    animal_tooth      = { name = 'animal_tooth',      label = 'Animal Tooth',      weight = 100, type = 'item', image = 'animal_tooth.png',      unique = false, useable = true, shouldClose = true, description = 'Animal tooth used as a crafting material' },
    animal_fang       = { name = 'animal_fang',       label = 'Animal Fang',       weight = 100, type = 'item', image = 'animal_fang.png',       unique = false, useable = true, shouldClose = true, description = 'Sharp fang taken from a predator' },
    animal_claw       = { name = 'animal_claw',       label = 'Animal Claw',       weight = 100, type = 'item', image = 'animal_claw.png',       unique = false, useable = true, shouldClose = true, description = 'Sharp animal claw' },
    animal_horn       = { name = 'animal_horn',       label = 'Animal Horn',       weight = 100, type = 'item', image = 'animal_horn.png',       unique = false, useable = true, shouldClose = true, description = 'Horn taken from a hunted animal' },
    animal_antler     = { name = 'animal_antler',     label = 'Animal Antler',     weight = 100, type = 'item', image = 'animal_antler.png',     unique = false, useable = true, shouldClose = true, description = 'Antler taken from a deer, elk, or moose' },
    animal_tusk       = { name = 'animal_tusk',       label = 'Animal Tusk',       weight = 100, type = 'item', image = 'animal_tusk.png',       unique = false, useable = true, shouldClose = true, description = 'Tusk taken from a large animal' },
    animal_hoof       = { name = 'animal_hoof',       label = 'Animal Hoof',       weight = 100, type = 'item', image = 'animal_hoof.png',       unique = false, useable = true, shouldClose = true, description = 'Hoof taken from a hunted animal' },
    animal_tail       = { name = 'animal_tail',       label = 'Animal Tail',       weight = 100, type = 'item', image = 'animal_tail.png',       unique = false, useable = true, shouldClose = true, description = 'Tail taken from a hunted animal' },
    animal_eye        = { name = 'animal_eye',        label = 'Animal Eye',        weight = 100, type = 'item', image = 'animal_eye.png',        unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Preserved eye taken from a hunted animal' },

    -- bird materials
    flight_feather    = { name = 'flight_feather',    label = 'Flight Feather',    weight = 100, type = 'item', image = 'flight_feather.png',    unique = false, useable = true, shouldClose = true, description = 'Strong feather suitable for crafting arrows' },
    eagle_feather     = { name = 'eagle_feather',     label = 'Eagle Feather',     weight = 100, type = 'item', image = 'eagle_feather.png',     unique = false, useable = true, shouldClose = true, description = 'Rare feather taken from an eagle' },
    hawk_feather      = { name = 'hawk_feather',      label = 'Hawk Feather',      weight = 100, type = 'item', image = 'hawk_feather.png',      unique = false, useable = true, shouldClose = true, description = 'Feather taken from a hawk' },
    owl_feather       = { name = 'owl_feather',       label = 'Owl Feather',       weight = 100, type = 'item', image = 'owl_feather.png',       unique = false, useable = true, shouldClose = true, description = 'Feather taken from an owl' },
    vulture_feather   = { name = 'vulture_feather',   label = 'Vulture Feather',   weight = 100, type = 'item', image = 'vulture_feather.png',   unique = false, useable = true, shouldClose = true, description = 'Feather taken from a vulture' },
    turkey_feather    = { name = 'turkey_feather',    label = 'Turkey Feather',    weight = 100, type = 'item', image = 'turkey_feather.png',    unique = false, useable = true, shouldClose = true, description = 'Feather taken from a wild turkey' },
    bird_beak         = { name = 'bird_beak',         label = 'Bird Beak',         weight = 100, type = 'item', image = 'bird_beak.png',         unique = false, useable = true, shouldClose = true, description = 'Beak taken from a hunted bird' },

    -- harvested carcasses
    animal_carcass    = { name = 'animal_carcass',    label = 'Animal Carcass',    weight = 100, type = 'item', image = 'animal_carcass.png',    unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Unprocessed animal carcass' },
    small_game_carcass = { name = 'small_game_carcass', label = 'Small Game Carcass', weight = 100, type = 'item', image = 'small_game_carcass.png', unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Unprocessed small-game carcass' },
    bird_carcass      = { name = 'bird_carcass',      label = 'Bird Carcass',      weight = 100, type = 'item', image = 'bird_carcass.png',      unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Unprocessed bird carcass' },
    rabbit_carcass    = { name = 'rabbit_carcass',    label = 'Rabbit Carcass',    weight = 100, type = 'item', image = 'rabbit_carcass.png',    unique = false, useable = true, decay = 180, delete = true, shouldClose = true, description = 'Unprocessed rabbit carcass' },

}
